### ISSUE TITLE
Automate the makefile

### ISSUE THREAD

**Issue by pydanny** [pydanny/listo#13]
This blog post document explains what I want to do. https://daniel.feldroy.com/posts/autodocumenting-makefiles

**Comment by YaswanthDasamandam** [comment]
Hi, I am new here I came here after seeing the "good first issue" lable, I kind of get what listo means . I would like to do the changes But I didnt understand what the automate the makefile is can you explain

**Comment by pydanny** [comment]
Please read the blog article to see what I want added to the makefile.

**Comment by YaswanthDasamandam** [comment]
I have done the [PR](https://github.com/pydanny/listo/pull/24)  please review

**Comment by pydanny** [comment]
Completed by @dysai1234. Thanks for all your hard work!
